language: go
go:
- 1.11.x
env:
- GO111MODULE=on
install:
- go mod vendor

before_script:
- go vet -v $(go list ./... | grep -v vendor)

matrix:
  include:
  - go: "1.11.x"
    script: go test -v -race -mod=vendor ./...

